name: ESLint
on:
  push:
    branches:
      - "!dependabot/*"
      - "*"
  pull_request:
    branches:
      - "!dependabot/*"
      - "*"
jobs:
  test:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node v16
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint
